// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLqIA9dOCWMxyKZM5kgHVwUJy4Kuuv1B4',
    appId: '1:755805731317:web:8ff8170788c60ea05c48bc',
    messagingSenderId: '755805731317',
    projectId: 'wilson-tours-541b9',
    authDomain: 'wilson-tours-541b9.firebaseapp.com',
    storageBucket: 'wilson-tours-541b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh6vCcbYh2nQF7PISoGwtvFj-5rN56ckE',
    appId: '1:755805731317:android:fb122418038ab6645c48bc',
    messagingSenderId: '755805731317',
    projectId: 'wilson-tours-541b9',
    storageBucket: 'wilson-tours-541b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEKk8Yjf6Uchv9Cc0z7X7EpEiaRJHZqXo',
    appId: '1:755805731317:ios:013bfc074bba77c15c48bc',
    messagingSenderId: '755805731317',
    projectId: 'wilson-tours-541b9',
    storageBucket: 'wilson-tours-541b9.appspot.com',
    iosClientId: '755805731317-f1on2irbnshoi4b2gulu2nd35rujflki.apps.googleusercontent.com',
    iosBundleId: 'com.example.wilsonToursApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEKk8Yjf6Uchv9Cc0z7X7EpEiaRJHZqXo',
    appId: '1:755805731317:ios:013bfc074bba77c15c48bc',
    messagingSenderId: '755805731317',
    projectId: 'wilson-tours-541b9',
    storageBucket: 'wilson-tours-541b9.appspot.com',
    iosClientId: '755805731317-f1on2irbnshoi4b2gulu2nd35rujflki.apps.googleusercontent.com',
    iosBundleId: 'com.example.wilsonToursApp',
  );
}
